spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    #SPRING_DATASOURCE_URL environment variable will be something like -> jdbc:sqlserver://MySqlServer\\MyInstance:1433;DatabaseName=MyDbName;
    url: jdbc:sqlserver://laxmivenkat.database.windows.net:1433;database=laxmivenkat;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=180;
    username: dbadmin
    password: Laxmivenkat@24
    driverClassName: org.hibernate.dialect.SQLServerDialect
